version: 1
merge:
  trigger:
    comment_substrings: ["Automated version updates"]
    auto_merge: true
  ignore:
    labels: ["do not merge"]
  method: squash
  required_statuses:
    - "policy-bot: master"
  delete_after_merge: true
